package com.image.collection.sql;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.image.collection.sql.CollectionModel;

import com.image.collection.sql.CollectionModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionModelDaoConfig;

    private final CollectionModelDao collectionModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionModelDaoConfig = daoConfigMap.get(CollectionModelDao.class).clone();
        collectionModelDaoConfig.initIdentityScope(type);

        collectionModelDao = new CollectionModelDao(collectionModelDaoConfig, this);

        registerDao(CollectionModel.class, collectionModelDao);
    }
    
    public void clear() {
        collectionModelDaoConfig.clearIdentityScope();
    }

    public CollectionModelDao getCollectionModelDao() {
        return collectionModelDao;
    }

}
